# Pseudo Labels generator, contain morphological prototypes generation and Pseudo Labels generation
import math
import torch
import torch.nn as nn
import torch.nn.functional as F
from typing import Dict, List, Tuple, Any
from torchvision.ops import RoIAlign
from torchvision.models.detection.rpn import AnchorGenerator, RPNHead, RegionProposalNetwork
from torchvision.models.detection.image_list import ImageList
from torchvision.models.detection.roi_heads import RoIHeads
from torchvision.models.detection.faster_rcnn import FastRCNNPredictor, TwoMLPHead
from torchvision.ops import MultiScaleRoIAlign
from torchvision.ops import RoIAlign
from torchvision.ops import batched_nms, box_iou


from .prototype_builder import ProtypeBuilder, build_prototype_builder_model
from .configs.cfg_mp_rcnn import MPRCNNConfig, build_mp_rcnn_config


class PL_generator(nn.Module):
    def __init__(
        self,
        p_builder: ProtypeBuilder,
        cfg: MPRCNNConfig,
    )-> None:
        super().__init__()

        self.p_builder = p_builder
        self.cfg = cfg

        # RoI Align for mid feature maps to proposals
        self.roi_align_m2p = RoIAlign(
            output_size=self.cfg.roi_out_size_m2p,
            spatial_scale=self.cfg.spatial_scale_m2p,
            sampling_ratio=self.cfg.sampling_ratio,
            aligned=self.cfg.aligned,
        )

    
    def _get_sparse_proposals(
        self,
        dense_proposals_list: List[torch.Tensor],  # dense proposals generated by RPN, len=B, each element is [N_d=num_dense_proposals, 4=(x1, y1, x2, y2)], origin coordinate
        wboxes: torch.Tensor,  # weak boxes for training, [R=num_wbs, 5=(batch_idx, x1, y1, x2, y2)]
        wb_labels: torch.Tensor,  # class label for weak boxes, one-hot, [R, N_c=num_classes], range [0, N_c - 1]
        keep_iou_thr: float = 0.5   # if no proposals completely inside any wbox, keep proposals whose max IoU with any wbox >= iou threshold, suggested range [0.5, 0.8]
    )-> Tuple[List[torch.Tensor], List[torch.Tensor]]:
        '''
        :return:
            sparse_proposals_list(List[torch.Tensor]): list of sparse proposals, len=B, each element is [N_s=num_sparse_proposals, 4=(x1, y1, x2, y2)], origin coordinate
            sparse_proposal_labels_list(List[torch.Tensor]): list of sparse proposal class labels, len=B, each element is [N_s], range [0, N_c - 1]
        '''
        B = len(dense_proposals_list)
        sparse_proposals_list = []
        sparse_proposal_labels_list = []

        for b in range(B):
            # all proposals in this image
            props_xyxy = dense_proposals_list[b]    # [num_props, 4]

            # all weak boxes in this image
            wb_mask = (wboxes[:, 0].long() == b)    # bool mask for wboxes in this image, shape [R]
            wbs = wboxes[wb_mask, 1:5]  # [num_wbs, 4]
            wbl = wb_labels[wb_mask]  # one-hot class labels for wboxes in this image, shape [num_wbs, num_classes], range [0, num_classes - 1]

            # completely inside wbox
            # broadcast
            p = props_xyxy[:, None, :]  # [num_props, 1, 4]
            w = wbs[None, :, :]  # [1, num_wbs, 4]
            # inside matrix, shape [num_props, num_wbs]
            inside = (p[..., 0] >= w[..., 0]) & (p[..., 1] >= w[..., 1]) & \
                     (p[..., 2] <= w[..., 2]) & (p[..., 3] <= w[..., 3])
            # iou matrix for proposals and wboxes, shape [num_props, num_wbs]
            ious = box_iou(props_xyxy, wbs)

            # initial sparse mask: any inside
            sparse_mask = inside.any(dim=1)  # [num_props]

            # no proposals completely inside any wbox, keep at least one proposal
            if not sparse_mask.any():
                max_iou_per_prop, _ = ious.max(dim=1)  # [num_props]
                # keep proposals whose max IoU with any wbox >= iou threshold
                iou_keep = max_iou_per_prop >= float(keep_iou_thr)  # [num_props]
                if iou_keep.any():
                    sparse_mask = iou_keep
                else:   # no proposals whose max IoU with any wbox >= iou threshold
                    # keep the proposal with highest IoU with any wbox
                    best_idx = torch.argmax(max_iou_per_prop)
                    sparse_mask = torch.zeros_like(max_iou_per_prop, dtype=torch.bool)
                    sparse_mask[best_idx] = True

            # assign class labels for sparse proposals based on wboxes
            # if proposal inside multiple wboxes: pick max IoU among inside ones for assign label
            big_neg = torch.finfo(ious.dtype).min   # large negative value for masking
            # for each proposal, get the max IoU with wboxes that it is inside of; if not inside any wbox, assign big negative
            masked_ious = torch.where(inside, ious, torch.tensor(big_neg, device=ious.device, dtype=ious.dtype))    # [num_props, num_wbs]
            wbox_best_inside = torch.argmax(masked_ious, dim=1)  # [num_props]
            wbox_best_iou = torch.argmax(ious, dim=1)  # [num_props]

            # for sparse proposals: choose best_inside if truly inside; else best_iou
            use_inside = inside.any(dim=1)
            wbox_best = torch.where(use_inside, wbox_best_inside, wbox_best_iou)  # index of best wbox for each proposal, shape [num_props]

            # assign labels for sparse proposals
            assigned_wbl = wbl[wbox_best]   # [num_props, num_classes]
            prop_labels_all = torch.argmax(assigned_wbl, dim=1).long()  # [num_props], range [0, num_classes - 1]

            # store sparse
            sparse_props = props_xyxy[sparse_mask]
            sparse_labels = prop_labels_all[sparse_mask]

            sparse_proposals_list.append(sparse_props)
            sparse_proposal_labels_list.append(sparse_labels)
        
        return sparse_proposals_list, sparse_proposal_labels_list


    # Softmax-based
    # def _compute_fg_scores(
    #     self,
    #     dataset_prototypes: Dict[int, torch.Tensor],    # {class_id, prototype_embeddings_raw}, class_id in [0, N_c], 0 for bg
    #     sparse_embeddings_raw: torch.Tensor,        # sparse proposal patch embeddings, [N, Np, D]
    #     sparse_proposal_labels_list: List[torch.Tensor],     # list of sparse proposal class labels, len=B, each element is [N_s], range [0, N_c - 1]
    #     lse_alpha: float = 10.0,    # LSE alpha
    #     tau: float = 0.01
    # )-> torch.Tensor:
    #     '''
    #     :return:
    #         fg_scores(torch.Tensor): foreground scores of all sparse proposals, [N]
    #     '''
    #     # -----L2 Normalization-----
    #     sparse_embeddings_norm = F.normalize(sparse_embeddings_raw, dim=2)  # [N, Np, D]
        
    #     bg_prototype_raw = dataset_prototypes[0]  # [D]
        
    #     prototypes_list = []
    #     for class_id in dataset_prototypes.keys():
    #         if class_id == 0:
    #             continue
    #         prototypes_list.append(dataset_prototypes[class_id])  # [D]
    #     prototypes_raw = torch.stack(prototypes_list, dim=0)  # [N_c, D]

    #     bg_prototype_norm = F.normalize(bg_prototype_raw, dim=0)  # [D]
    #     prototypes_norm = F.normalize(prototypes_raw, dim=1)  # [N_c, D]


    #     # -----merge sparse embeddings-----
    #     sparse_embedding_merged_list = []
    #     for i in range(sparse_embeddings_norm.shape[0]):
    #         embedding = sparse_embeddings_norm[i]  # [Np, D]
    #         embedding_merged = torch.logsumexp(embedding * lse_alpha, dim=0) / lse_alpha  # [D]
    #         sparse_embedding_merged_list.append(embedding_merged)
    #     sparse_embeddings_merged_norm = torch.stack(sparse_embedding_merged_list, dim=0)  # [N, D]


    #     # -----Compute fg scores-----
    #     z = sparse_embeddings_merged_norm       # [N, D]
    #     eta_bg = bg_prototype_norm      # [D]
    #     eta_fg = prototypes_norm     # [N_c, D]
    #     sparse_proposal_labels = torch.cat(sparse_proposal_labels_list, dim=0)  # [N]
    #     num_classes = eta_fg.shape[0]

    #     fg_scores = torch.zeros(z.shape[0], device=z.device)  # [N]
    #     for k in range(num_classes):
    #         mask_k = (sparse_proposal_labels == k)  # [N]
    #         indices_k = torch.nonzero(mask_k).squeeze(1)  # [N_k]
    #         if indices_k.numel() == 0:
    #             continue
    #         z_k = z[indices_k]  # [N_k, D]
    #         eta_k = eta_fg[k]  # [D]
    #         # for proposals in class k:
    #         # x = z_k @ eta_k - z_k @ eta_bg
    #         # s_k = softmax(x) / tau
    #         x = torch.matmul(z_k, eta_k) - torch.matmul(z_k, eta_bg)  # [N_k]
    #         s_k = F.softmax(x / tau, dim=0)  # [N_k]
    #         fg_scores[indices_k] = s_k  # assign scores for class k
        
    #     return fg_scores


    # origin margin
    def _compute_fg_scores(
        self,
        dataset_prototypes: Dict[int, torch.Tensor],    # {class_id, prototype_embeddings_raw}, class_id in [0, N_c], 0 for bg
        sparse_embeddings_raw: torch.Tensor,        # sparse proposal patch embeddings, [N, Np, D]
        sparse_proposal_labels_list: List[torch.Tensor],     # list of sparse proposal class labels, len=B, each element is [N_s], range [0, N_c - 1]
        lse_alpha: float = 10.0,    # LSE alpha
    )-> torch.Tensor:
        '''
        :return:
            fg_scores(torch.Tensor): foreground scores of all sparse proposals, [N]
        '''
        # -----L2 Normalization-----
        sparse_embeddings_norm = F.normalize(sparse_embeddings_raw, dim=2)  # [N, Np, D]
            
        bg_prototype_raw = dataset_prototypes[0]  # [D]
            
        prototypes_list = []
        for class_id in dataset_prototypes.keys():
            if class_id == 0:
                continue
            prototypes_list.append(dataset_prototypes[class_id])  # [D]
        prototypes_raw = torch.stack(prototypes_list, dim=0)  # [N_c, D]
    
        bg_prototype_norm = F.normalize(bg_prototype_raw, dim=0)  # [D]
        prototypes_norm = F.normalize(prototypes_raw, dim=1)  # [N_c, D]
    
    
        # -----merge sparse embeddings-----
        sparse_embedding_merged_list = []
        for i in range(sparse_embeddings_norm.shape[0]):
            embedding = sparse_embeddings_norm[i]  # [Np, D]
            embedding_merged = torch.logsumexp(embedding * lse_alpha, dim=0) / lse_alpha  # [D]
            sparse_embedding_merged_list.append(embedding_merged)
        sparse_embeddings_merged_norm = torch.stack(sparse_embedding_merged_list, dim=0)  # [N, D]
    
    
        # -----Compute fg scores-----
        z = sparse_embeddings_merged_norm       # [N, D]
        eta_bg = bg_prototype_norm      # [D]
        eta_fg = prototypes_norm     # [N_c, D]
        sparse_proposal_labels = torch.cat(sparse_proposal_labels_list, dim=0)  # [N]
        fg_scores = torch.zeros(z.shape[0], device=z.device)  # [N]
        for i in range(z.shape[0]):
            k = sparse_proposal_labels[i]
            z_i = z[i]  # [D]
            eta_k = eta_fg[k]   # [D]
            # pos_sim: positive similarity with its class prototype
            # pos_sim = z_i @ eta_k
            pos_sim = torch.matmul(z_i, eta_k)
            # neg_sim: negative similarity with background prototype
            # neg_sim = z_i @ eta_bg
            neg_sim = torch.matmul(z_i, eta_bg)
            # s_i: foreground score for this proposal, margin style
            # s_i = pos_sim - neg_sim
            s_i = pos_sim - neg_sim
            fg_scores[i] = s_i  # assign score for this proposal

        return fg_scores


    def _compute_thresholds(
        self,
        dataset_prototypes: Dict[int, torch.Tensor],    # {class_id, prototype_embeddings_raw}, class_id in [0, N_c], 0 for bg
        sparse_embeddings_raw: torch.Tensor,        # sparse proposal patch embeddings, [N, Np, D]
        sparse_proposal_labels_list: List[torch.Tensor],     # list of sparse proposal class labels, len=B, each element is [N_s], range [0, N_c - 1]
        top_indices: torch.Tensor,    # top-score proposal indices for each class, [N_c]
        lse_alpha: float = 10.0    # LSE alpha
    )-> List[float]:
        '''
        :return:
            threshold_list(List[float]): len=N_c, list of thresholds for each class
        '''
        # -----merge sparse embeddings-----
        sparse_embedding_merged_list = []
        for i in range(sparse_embeddings_raw.shape[0]):
            embedding = sparse_embeddings_raw[i]  # [N_p, D]
            embedding_merged = torch.logsumexp(embedding * lse_alpha, dim=0) / lse_alpha  # [D]
            sparse_embedding_merged_list.append(embedding_merged)
        sparse_embeddings_merged_raw = torch.stack(sparse_embedding_merged_list, dim=0)  # [N, D]

        # -----L2 Normalization-----
        sparse_embeddings_merged_norm = F.normalize(sparse_embeddings_merged_raw, dim=1)  # [N, D]
        
        prototypes_list = []
        for class_id in dataset_prototypes.keys():
            if class_id == 0:
                continue
            prototypes_list.append(dataset_prototypes[class_id])  # [D]
        prototypes_raw = torch.stack(prototypes_list, dim=0)  # [N_c, D]
        prototypes_norm = F.normalize(prototypes_raw, dim=1)  # [N_c, D]

        # -----Compute thresholds-----
        sparse_proposal_labels = torch.cat(sparse_proposal_labels_list, dim=0)  # [N]
        top_score_embeddings = sparse_embeddings_merged_norm[top_indices]  # [N_c, D]
        num_classes = prototypes_norm.shape[0]
        threshold_list = []
        for k in range(num_classes):
            mask_k = (sparse_proposal_labels == k)  # [N]
            if mask_k.sum() == 0:
                threshold_list.append(0.0)  # no proposals for class k, set threshold to 0
                continue
            eta_k = prototypes_norm[k]  # [D]
            z_top_k = top_score_embeddings[k]  # [D]
            # threshold of class k: t_k = z_top_k @ eta_k^T
            t_k = torch.matmul(z_top_k, eta_k)
            threshold_list.append(t_k.item())
        
        return threshold_list


    def _build_pseudo_labels(
        self,
        sparse_embeddings_raw: torch.Tensor,        # sparse proposal patch embeddings, [N, Np, D]
        sparse_proposal_labels_list: List[torch.Tensor],     # list of sparse proposal class labels, len=B, each element is [N_s], range [0, N_c - 1]
        top_indices: torch.Tensor,    # top-score proposal indices for each class, [N_c]
        threshold_list: List[float],    # list of thresholds for each class, len=N_c
        sparse_proposals_list: List[torch.Tensor],     # list of sparse proposals, len=B, each element is [N_s, 4=(x1, y1, x2, y2)], origin coordinate
        fg_scores: torch.Tensor,    # foreground scores of all sparse proposals, [N]
        lse_alpha: float = 10.0,    # LSE alpha
        nms_thresh: float = 0.5,    # NMS IoU threshold
        topk_ratio_per_class: float = 0.25,    # top-k selection ratio, [0.1, 0.5]
    )-> List[Dict[str, torch.Tensor]]:
        '''
        :return:
            batch_pseudo_labels(List[Dict[str, torch.Tensor]]): batch pseudo labels, len=B, each element contains:
            - 'boxes'(torch.Tensor): [N_pl=num_pseudo_labels, 4=(x1, y1, x2, y2)]
            - 'scores'(torch.Tensor): [N_pl]
            - 'labels'(torch.Tensor): [N_pl], range [1, N_c], 0 for bg
        '''
        if not 0.0 < topk_ratio_per_class <= 1.0:
            raise ValueError(
                "topk_ratio_per_class 必须位于 (0, 1] 范围内，"
                f"当前值为 {topk_ratio_per_class}"
            )

        # -----merge & L2 normalize sparse embeddings-----
        sparse_embedding_merged_list = []
        for i in range(sparse_embeddings_raw.shape[0]):
            embedding = sparse_embeddings_raw[i]  # [N_p, D]
            embedding_merged = torch.logsumexp(embedding * lse_alpha, dim=0) / lse_alpha  # [D]
            sparse_embedding_merged_list.append(embedding_merged)
        sparse_embeddings_merged_raw = torch.stack(sparse_embedding_merged_list, dim=0)  # [N, D]
        sparse_embeddings_merged_norm = F.normalize(sparse_embeddings_merged_raw, dim=1)  # [N, D]
        top_score_embeddings_norm = sparse_embeddings_merged_norm[top_indices]  # [N_c, D]

        # -----Scan all proposals-----
        sparse_proposal_labels = torch.cat(sparse_proposal_labels_list, dim=0)  # [N]
        num_classes = top_score_embeddings_norm.shape[0]
        keep_indices_list = []  # len=N_c, each element is indices of proposals to keep for class k
        for k in range(num_classes):
            mask_k = (sparse_proposal_labels == k)  # [N]
            if mask_k.sum() == 0:
                tmp = torch.tensor([], dtype=torch.long, device=sparse_embeddings_merged_norm.device)
                keep_indices_list.append(tmp)
                continue
            props_indices_k = torch.nonzero(mask_k).squeeze(1)  # [N_k]
            z_k = sparse_embeddings_merged_norm[props_indices_k]  # [N_k, D]
            z_top_k = top_score_embeddings_norm[k]  # [D]
            # compute similarity scores for class k: 
            # sims = z_k @ z_top_k^T
            sims = torch.matmul(z_k, z_top_k)  # [N_k]
            # select proposals whose similarity scores >= threshold and fg_score > 0 for class k
            t_k = threshold_list[k]
            selected_mask = (sims >= t_k) & (fg_scores[props_indices_k] > 0)  # [N_k]
            keep_indices = props_indices_k[selected_mask]  # [N_keep_k]
            keep_indices_list.append(keep_indices)
        
        # -----Build batch pseudo labels-----
        batch_pseudo_labels : List[Dict[str, torch.Tensor]] = []
        proposal_offset = 0
        for proposals_b in sparse_proposals_list:
            proposal_end = proposal_offset + proposals_b.shape[0]
            boxes_b = []
            scores_b = []
            labels_b = []

            for k, keep_indices in enumerate(keep_indices_list):
                in_image_mask = (keep_indices >= proposal_offset) & (keep_indices < proposal_end)
                global_indices = keep_indices[in_image_mask]
                if global_indices.numel() == 0:
                    continue

                image_indices = global_indices - proposal_offset
                boxes_b.append(proposals_b[image_indices])
                scores_b.append(fg_scores[global_indices])
                labels_b.append(torch.full(
                    (image_indices.numel(),),
                    k + 1,
                    dtype=torch.long,
                    device=proposals_b.device,
                ))

            if boxes_b:
                boxes = torch.cat(boxes_b, dim=0)
                scores = torch.cat(scores_b, dim=0)
                labels = torch.cat(labels_b, dim=0)

                # NMS
                nms_keep_indices = batched_nms(
                    boxes=boxes,
                    scores=scores,
                    idxs=labels,
                    iou_threshold=nms_thresh,
                )

                # Top-k Selection
                nms_labels = labels[nms_keep_indices]
                class_topk_indices = []
                for class_id in torch.unique(nms_labels):
                    class_mask = nms_labels == class_id
                    class_indices = nms_keep_indices[class_mask]
                    class_scores = scores[class_indices]
                    num_keep = math.ceil(
                        class_indices.numel() * topk_ratio_per_class
                    )
                    _, class_score_order = torch.topk(
                        class_scores,
                        k=num_keep,
                        largest=True,
                        sorted=True,
                    )
                    class_topk_indices.append(class_indices[class_score_order])

                topk_keep_indices = torch.cat(class_topk_indices, dim=0)

                score_order = torch.argsort(
                    scores[topk_keep_indices],
                    descending=True,
                )
                topk_keep_indices = topk_keep_indices[score_order]

                pseudo_labels_b = {
                    'boxes': boxes[topk_keep_indices],
                    'scores': scores[topk_keep_indices],
                    'labels': labels[topk_keep_indices],
                }
            else:
                pseudo_labels_b = {
                    'boxes': proposals_b.new_empty((0, 4)),
                    'scores': fg_scores.new_empty((0,)),
                    'labels': torch.empty((0,), dtype=torch.long, device=proposals_b.device),
                }

            batch_pseudo_labels.append(pseudo_labels_b)
            proposal_offset = proposal_end

        return batch_pseudo_labels


    def _object_discovery(
        self,
        dataset_prototypes: Dict[int, torch.Tensor],    # {class_id, prototype_embeddings_raw}, class_id in [0, N_c], 0 for bg
        sparse_embeddings_raw: torch.Tensor,        # sparse proposal patch embeddings, [N, Np, D]
        sparse_proposal_labels_list: List[torch.Tensor],     # list of sparse proposal class labels, len=B, each element is [N_s], range [0, N_c - 1]
        sparse_proposals_list: List[torch.Tensor]     # list of sparse proposals, len=B, each element is [N_s, 4=(x1, y1, x2, y2)], origin coordinate
    )-> List[Dict[str, torch.Tensor]]:
        '''
        :return: 
            batch_pseudo_labels(List[Dict[str, torch.Tensor]]): batch pseudo labels, len=B, each element contains:
            - 'boxes'(torch.Tensor): [N_pl=num_pseudo_labels, 4=(x1, y1, x2, y2)]
            - 'scores'(torch.Tensor): [N_pl]
            - 'labels'(torch.Tensor): [N_pl], range [1, N_c], 0 for bg
        '''
        # -----Compute fg scores-----
        fg_scores = self._compute_fg_scores(
            dataset_prototypes, 
            sparse_embeddings_raw, 
            sparse_proposal_labels_list
        )     # [N]

        # -----Select top-score proposals-----
        sparse_proposal_labels = torch.cat(sparse_proposal_labels_list, dim=0)  # [N]
        num_classes = len(dataset_prototypes) - 1
        topk = 1
        top_indices = torch.full(
            (num_classes,),
            -1,
            dtype=torch.long,
            device=sparse_proposal_labels.device,
        )
        for k in range(num_classes):
            mask_k = (sparse_proposal_labels == k)
            indices_k = torch.nonzero(mask_k).squeeze(1)
            if indices_k.numel() == 0:
                continue
            fg_scores_k = fg_scores[indices_k]
            _, topk_indices = torch.topk(fg_scores_k, k=topk)
            top_indices[k] = indices_k[topk_indices[0]]

        
        # ----Compute threshold-----
        threshold_list = self._compute_thresholds(
            dataset_prototypes, 
            sparse_embeddings_raw, 
            sparse_proposal_labels_list, 
            top_indices
        )      # len=N_c, each element is threshold for class k
        
        # -----Discover objects-----
        batch_pseudo_labels = self._build_pseudo_labels(
            sparse_embeddings_raw, 
            sparse_proposal_labels_list, 
            top_indices,
            threshold_list,
            sparse_proposals_list,
            fg_scores
        )

        return batch_pseudo_labels
    

    def forward(
        self,
        x: torch.Tensor,  # mid-level feature maps, [B, C2=C_of_mid, H2=H_of_mid, W2=W_of_mid]
        dense_proposals_list: List[torch.Tensor],  # dense proposals generated by RPN, len=B, each element is [N_d=num_dense_proposals, 4=(x1, y1, x2, y2)], origin coordinate
        wboxes: torch.Tensor,  # weak boxes for training, [R=num_wbs, 5=(batch_idx, x1, y1, x2, y2)]
        wb_labels: torch.Tensor,  # class label for weak boxes, one-hot, [R, N_c=num_classes], range [0, N_c - 1]
        dataset_prototypes: Dict[int, torch.Tensor],    # {class_id, prototype_embeddings_raw}, class_id in [0, N_c], 0 for bg
    )-> List[Dict[str, torch.Tensor]]:
        '''
        :return: 
            batch_pseudo_labels(List[Dict[str, torch.Tensor]]): batch pseudo labels, len=B, each element contains:
            - 'boxes'(torch.Tensor): [N_pl=num_pseudo_labels, 4=(x1, y1, x2, y2)]
            - 'scores'(torch.Tensor): [N_pl]
            - 'labels'(torch.Tensor): [N_pl], range [1, N_c], 0 for bg
        '''
        # -----Split dense proposals into sparse proposals and bg proposals based on wboxes-----
        sparse_proposals_list, sparse_proposal_labels_list = self._get_sparse_proposals(dense_proposals_list, wboxes, wb_labels)
        
        # -----Get sparse roi feature embeddings-----
        # RoI Align
        sparse_roi_features = self.roi_align_m2p(x, sparse_proposals_list)      # [N=num_proposals, C, H_roi, W_roi]
        # Patch Embed
        sparse_patch_embeddings = self.p_builder.mp_generator.patch_embed(sparse_roi_features)      # [N, Np=num_patches, D=embed_dim]
        # Project
        sparse_embeddings_raw = self.p_builder.projector(sparse_patch_embeddings)   # [N, Np, D]

        # -----Object Discovery-----
        batch_pseudo_labels = self._object_discovery(
            dataset_prototypes, 
            sparse_embeddings_raw, 
            sparse_proposal_labels_list,
            sparse_proposals_list
        )

        return batch_pseudo_labels



class MPRCNN(nn.Module):
    def __init__(
        self,
        p_builder: ProtypeBuilder,
        pl_generator: PL_generator,
        cfg: MPRCNNConfig
    )-> None:
        super().__init__()

        self.p_builder = p_builder
        self.pl_generator = pl_generator
        self.cfg = cfg


        # RoI Align for high-level feature maps to proposal box feature maps
        self.roi_align_h2p = MultiScaleRoIAlign(
            featmap_names=["0"],
            output_size=self.cfg.roi_out_size_h2p,
            sampling_ratio=self.cfg.sampling_ratio,
        )

        # RPN
        anchor_generator = AnchorGenerator(
            sizes=(self.cfg.rpn_anchor_sizes,),
            aspect_ratios=(self.cfg.rpn_anchor_aspect_ratios,)
        )
        rpn_head = RPNHead(in_channels=self.cfg.in_c, num_anchors=anchor_generator.num_anchors_per_location()[0])
        self.rpn = RegionProposalNetwork(
            anchor_generator=anchor_generator,
            head=rpn_head,
            fg_iou_thresh=self.cfg.rpn_fg_iou_thresh,
            bg_iou_thresh=self.cfg.rpn_bg_iou_thresh,
            batch_size_per_image=self.cfg.rpn_batch_size_per_image,
            positive_fraction=0.5,
            pre_nms_top_n={"training": self.cfg.rpn_pre_nms_top_n['training'],
                           "testing": self.cfg.rpn_pre_nms_top_n['testing']},
            post_nms_top_n={"training": self.cfg.rpn_post_nms_top_n['training'],
                            "testing": self.cfg.rpn_post_nms_top_n['testing']},
            nms_thresh=self.cfg.rpn_nms_thresh
        )

        # Box Head
        resolution = self.cfg.roi_out_size_h2p
        box_head = TwoMLPHead(
            in_channels=self.cfg.in_c * resolution * resolution,
            representation_size=self.cfg.hidden_dim,
        )
        
        # Box Predictor
        box_predictor = FastRCNNPredictor(
            in_channels=self.cfg.hidden_dim,
            num_classes=self.cfg.num_classes + 1,  # include background
        )
        
        # RoI Heads (roi align + box head + box predictor)
        self.roi_heads = RoIHeads(
            box_roi_pool=self.roi_align_h2p,
            box_head=box_head,
            box_predictor=box_predictor,
        
            fg_iou_thresh=self.cfg.det_fg_iou_thresh,
            bg_iou_thresh=self.cfg.det_bg_iou_thresh,
            batch_size_per_image=self.cfg.det_batch_size_per_image,
            positive_fraction=self.cfg.det_positive_fraction,
        
            bbox_reg_weights=None,
            score_thresh=self.cfg.det_score_thresh,
            nms_thresh=self.cfg.det_nms_thresh,
            detections_per_img=self.cfg.detections_per_img,
        )


    @torch.no_grad()
    def _get_dense_proposals(
        self,
        feature_maps: torch.Tensor,  # high-level feature maps, shape [B, C3, H3, W3]
        image_sizes: List[Tuple[int, int]],  # len=B, each element is (H, W)
        images_tensor: torch.Tensor  # for ImageList format
    )-> List[torch.Tensor]:
        '''
        :return:
            dense_proposals_list(List[torch.Tensor]):len=B, each element is [N_d=num_dense_proposals, 4=(x1, y1, x2, y2)], origin coordinate
        '''
        self.rpn.eval()
        img_list = ImageList(tensors=images_tensor, image_sizes=image_sizes)
        features = {"0": feature_maps}
        dense_proposals_list, _ = self.rpn(img_list, features)

        return dense_proposals_list


    def _forward_train(
        self,
        x: torch.Tensor,  # input images, [B, C, H, W]
        dataset_prototypes: Dict[int, torch.Tensor],    # {class_id, prototype_embeddings_raw}, class_id in [0, N_c=num_classes], 0 for bg
        wboxes: torch.Tensor,  # weak boxes for training, [R=num_wbs, 5], for each box, [batch_idx, x1, y1, x2, y2]
        wb_labels: torch.Tensor,  # class label for weak boxes, one-hot, [R, N_c], range [0, N_c - 1]
    )-> Dict[str, Any]:
        '''
        :return:
            out(Dict[str, Any]): output dictionary, contains:
            - 'rpn_losses_dict'(Dict[str, torch.Tensor]): RPN losses, contains:
                - 'loss_objectness'(torch.Tensor): objectness loss
                - 'loss_rpn_box_reg'(torch.Tensor): RPN box regression loss
            - 'det_losses_dict'(Dict[str, torch.Tensor]): Detection losses, contains:
                - 'loss_classifier'(torch.Tensor): classification loss
                - 'loss_box_reg'(torch.Tensor): box regression loss
        '''
        out = {}    # output
        # -----Get mid & high level feature maps-----
        feature_maps = self.p_builder.get_feature_maps(x)
        mid_feature_maps = feature_maps['mid']  # [B, C2=C_of_mid, H2=H_of_mid, W2=W_of_mid]
        high_feature_maps = feature_maps['high']      # [B, C3=C_of_high, H3=H_of_high, W3=W_of_high]
        

        # -----Generate Pseudo Labels-----
        # get dense proposals
        img_size = (x.shape[-2], x.shape[-1])  # (H, W)
        img_size_list = [img_size for _ in range(x.shape[0])]
        dense_proposal_list =  self._get_dense_proposals(high_feature_maps, img_size_list, x)
        # generate pseudo labels
        batch_pseudo_labels = self.pl_generator(
            x=mid_feature_maps, 
            dense_proposals_list=dense_proposal_list, 
            wboxes=wboxes,
            wb_labels=wb_labels,
            dataset_prototypes=dataset_prototypes
        )
        # debug
        self.batch_pseudo_labels = batch_pseudo_labels


        # -----Generate Proposals-----
        img_size = (x.shape[-2], x.shape[-1])  # (H, W)
        image_sizes = [img_size for _ in range(x.shape[0])]
        img_list = ImageList(tensors=x, image_sizes=image_sizes)
        features = {"0": high_feature_maps}
        self.rpn.train()
        proposals_list, rpn_losses_dict = self.rpn(
            img_list, 
            features, 
            batch_pseudo_labels
        )
        out.update({
            'rpn_losses_dict': rpn_losses_dict
        })


        # -----R-CNN Head-----
        _, det_losses_dict = self.roi_heads(
            features={"0": high_feature_maps},
            proposals=proposals_list,
            image_shapes=image_sizes,
            targets=batch_pseudo_labels
        )
        out.update({
            'det_losses_dict': det_losses_dict
        })

        return out
    

    def _forward_inference(
        self,
        x: torch.Tensor,  # input images, [B, C, H, W]
    )-> List[Dict[str, torch.Tensor]]:
        '''
        :return:
            detections(List[Dict[str, torch.Tensor]]): len=B, each element contains:
            - 'boxes'(torch.Tensor): predicted boxes, [N_det, 4=(x1, y1, x2, y2)]
            - 'labels'(torch.Tensor): [N_det], range [1, N_c=num_classes], 0 reserved for background
            - 'scores'(torch.Tensor): softmax confidence, [N_det]
        '''
        # ----Get high level feature maps-----
        self.p_builder.encoder[-1] = nn.Identity()  # remove the last layer of encoder to get high-level feature maps
        high_feature_maps = self.p_builder.encoder(x)  # [B, C3=C_of_high, H3=H_of_high, W3=W_of_high]

        # -----Generate Proposals-----
        img_size = (x.shape[-2], x.shape[-1])  # (H, W)
        image_sizes = [img_size for _ in range(x.shape[0])]
        img_list = ImageList(tensors=x, image_sizes=image_sizes)
        features = {"0": high_feature_maps}
        proposals_list, _ = self.rpn(img_list, features)

        # -----Get Detections-----
        detections = self.roi_heads(
            features={"0": high_feature_maps},
            proposals=proposals_list,
            image_shapes=image_sizes,
        )[0]
        
        return detections
    

    def forward(
        self,
        mode: str,  # 'train' or 'inference'
        x: torch.Tensor,  # input images, [B, C, H, W]
        dataset_prototypes: Dict[int, torch.Tensor] = None,    # {class_id, prototype_embeddings_raw}, class_id in [0, N_c=num_classes], 0 for bg
        wboxes: torch.Tensor = None,  # weak boxes for training, [R=num_wbs, 5], for each box, [batch_idx, x1, y1, x2, y2]
        wb_labels: torch.Tensor = None,  # class label for weak boxes, one-hot, [R, N_c], range [0, N_c - 1]
    )-> Any:
        if mode == 'train':
            return self._forward_train(
                x, 
                dataset_prototypes, 
                wboxes, 
                wb_labels
            )
        elif mode == 'inference':
            return self._forward_inference(x)
        else:
            raise ValueError(f"Invalid mode: {mode}. Expected 'train' or 'inference'.")
        

        
def build_mp_rcnn_model(
    cfg: Dict      # global configuration
)-> MPRCNN:
    p_builder = build_prototype_builder_model(cfg)
    # freeze p_builder parameters
    for param in p_builder.parameters():
        param.requires_grad = False

    model_cfg = build_mp_rcnn_config(cfg)
    pl_generator = PL_generator(p_builder, model_cfg)

    return MPRCNN(
        p_builder=p_builder,
        pl_generator=pl_generator,
        cfg=model_cfg
    )